### ISSUE TITLE
im tuned

### ISSUE THREAD

**Issue by Gentleman2292** [doctor-swag/moneymod-rewrite#1]
zamn bro ur gonna leak it 🥵

**Comment by doctor-swag** [comment]
tuned tuned tuned coming soon bro 12/12/21

**Comment by notperry1234567890** [comment]
> tuned tuned tuned coming soon bro 12/12/21

:trollface:

**Comment by doctor-swag** [comment]
> > tuned tuned tuned coming soon bro 12/12/21
> 
> :trollface:

decided to release it early :P

**Comment by Gentleman2292** [comment]
:trollface:

**Comment by Gentleman2292** [comment]
trolled successfully

**Comment by doctor-swag** [comment]
ez leaked rolling trolling done ez
