### ISSUE TITLE
mint client changelog went crazy mode after this one ❗❗❗

### ISSUE THREAD

**Issue by w0rl3x** [doctor-swag/moneymod-rewrite#4]

**Comment by doctor-swag** [comment]
oh shit!!!

**Comment by ProfKambing** [comment]
mint client is still a thing?

**Comment by ZenovJB** [comment]
doxbin.org/upload/w0rlex2b2t is goin crazy bro

**Comment by VikasLagerweij** [comment]
mint client still is being worked on??? didnt know that

**Comment by VikasLagerweij** [comment]
doxbin.org/upload/w0rlex2b2t is goin crazy bro

**Comment by VikasLagerweij** [comment]
nice one https://streamable.com/ex92ip https://streamable.com/ex92ip https://streamable.com/ex92ip https://streamable.com/ex92ip

**Comment by w0rl3x** [comment]
> nice one https://streamable.com/ex92ip https://streamable.com/ex92ip https://streamable.com/ex92ip https://streamable.com/ex92ip

u still being on mobile hotspot Man ❓

**Comment by VikasLagerweij** [comment]
doxbin.org/upload/w0rlex2b2t nice router bro

**Comment by w0rl3x** [comment]
> doxbin.org/upload/w0rlex2b2t nice router bro

ye boot me off :rofl: so poor to get a paid booter

**Comment by 3S0** [comment]
> > nice one https://streamable.com/ex92ip https://streamable.com/ex92ip https://streamable.com/ex92ip https://streamable.com/ex92ip
> 
> u still being on mobile hotspot Man ❓

💀

**Comment by 6sn** [comment]
2 still unknown retards arguing
