### ISSUE TITLE
Unloved Skid leaks outdated client

### ISSUE THREAD

**Issue by Skitttyy** [doctor-swag/moneymod-rewrite#6]
lel dumb skid this is why all your code in the clients you made are from cattyn and mironov lel really pasted his burrow into trinity+ that’s sad asf. lel define a array dumb paster ur obf will never be good

**Comment by Skitttyy** [comment]
Literally in college trying to sell a fucking pasted obf lel sad kid doesn’t even know asm yet taking java classes in college. eskid betaless zkm betaless but binsecure leakfull so makes pasted obf to use ontop of binsecure lel

**Comment by Skitttyy** [comment]
![00E9159C-0CB4-45DB-83DA-0375F53FCB55](https://user-images.githubusercontent.com/73967130/144757952-416b3270-5fbb-4252-a19c-6a62e96cd241.png)

**Comment by Skitttyy** [comment]
![B59428D2-6C3C-4A0D-8B6C-9733011B74F9](https://user-images.githubusercontent.com/73967130/144757983-9099c5fb-7bbb-4f4e-b3ce-c0da018b6bd1.png)

**Comment by Skitttyy** [comment]
Lel you cannot code lel ur in college crying about getting removed from a repo lel poor skid leaking outdated cheat lel in college playing minecraft you are so sad lel unknown newgen poor boy rando haha skidding obf too lel you cannot obf for any cookie crumbs random sad boy nn

**Comment by nwop1** [comment]
Lel

**Comment by pgshka** [comment]
kek

**Comment by doctor-swag** [comment]
russians coping coz their client leaked 🥶

**Comment by Skitttyy** [comment]
LOL geek thinks im a russian LOL! thats clipped af brokeboy 
![image](https://user-images.githubusercontent.com/73967130/148670151-e91e48a3-bc6d-4f71-acca-4367ee06d8ac.png)
LOL! that image is sad asf pooron has no gains + doesnt know what an accessor is thats clipped af dumb skid ur hack will go public af im in ur pc ur pc will get bombed
![image](https://user-images.githubusercontent.com/73967130/148670172-9492f275-d30e-4df0-8bf4-236802d0b7ab.png)
(chart of my bitcoin wallet handle) LOL im so rich brokeboy

**Comment by Skitttyy** [comment]
![image](https://user-images.githubusercontent.com/73967130/148670308-4cae2c78-1406-4fee-abf6-f6aa18f1483e.png)
im in ur pc u will die

**Comment by Skitttyy** [comment]
i have full control lel ur pc will get bombed
