### ISSUE TITLE
Lel random opp skid

### ISSUE THREAD

**Issue by nwop1** [doctor-swag/moneymod-rewrite#7]
Lel you cannot code lel ur in college crying about getting removed from a repo lel poor skid leaking outdated cheat lel in college playing minecraft you are so sad lel unknown newgen poor boy rando haha skidding obf too lel you cannot obf for any cookie crumbs random sad boy nn

**Comment by doctor-swag** [comment]
what in the fucking hell did i just read 💀

**Comment by 6sn** [comment]
even though nwop is mentally ill he said some fax man delete yo git

**Comment by 6sn** [comment]
who the fuck are you holy shit

**Comment by Razzleqq** [comment]
https://user-images.githubusercontent.com/90716445/147883732-ab85d5b2-0900-4044-b71e-6eb51b8906f2.MOV

**Comment by Razzleqq** [comment]
> https://user-images.githubusercontent.com/90716445/147883732-ab85d5b2-0900-4044-b71e-6eb51b8906f2.MOV

Real shit
